import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import {
  compareReleaseAssets,
  promoteReleaseAssets,
  releaseAssetsRequiredBetween
} from '../scripts/release-doc-assets.mjs';

const outputs = Object.freeze({
  en: { paper: 'LETTER', pdfPath: 'output/pdf/en-letter.pdf', screenshotPath: 'docs/screenshots/en.png' },
  ja: { paper: 'A4', pdfPath: 'output/pdf/ja-a4.pdf', screenshotPath: 'docs/screenshots/ja.png' },
  'zh-CN': { paper: 'A4', pdfPath: 'output/pdf/zh-CN-a4.pdf', screenshotPath: 'docs/screenshots/zh-CN.png' }
});

function digest(contents) {
  return createHash('sha256').update(contents).digest('hex');
}

async function writeAssetFixture(root, { commit, lfsPointers = false, siteHash = 'c'.repeat(64), version = '0.3.0' }) {
  await mkdir(path.join(root, 'docs/screenshots'), { recursive: true });
  await mkdir(path.join(root, 'output/pdf'), { recursive: true });
  await writeFile(path.join(root, 'package.json'), `${JSON.stringify({ version })}\n`);
  const manifestOutputs = [];
  for (const [locale, expected] of Object.entries(outputs)) {
    const records = {};
    for (const [kind, relativePath] of [['screenshot', expected.screenshotPath], ['pdf', expected.pdfPath]]) {
      const contents = Buffer.from(`${locale}-${kind}-fixture`);
      const sha256 = digest(contents);
      const stored = lfsPointers
        ? `version https://git-lfs.github.com/spec/v1\noid sha256:${sha256}\nsize ${contents.length}\n`
        : contents;
      await writeFile(path.join(root, relativePath), stored);
      records[kind] = kind === 'screenshot'
        ? { fixture: 'fictional-documentation-example', height: 1000, path: relativePath, sha256, width: 1440 }
        : { fixture: 'deterministic-print-example', path: relativePath, sha256 };
    }
    manifestOutputs.push({
      browserLocale: locale, firstText: `first-${locale}`, lastText: `last-${locale}`, locale,
      marker: `marker-${locale}`, paper: expected.paper, ...records
    });
  }
  const manifest = {
    schemaVersion: 2,
    generator: { path: 'scripts/generate-doc-assets.mjs', version: '1.3.0' },
    source: { appVersion: version, commit, siteHash },
    outputs: manifestOutputs
  };
  await writeFile(path.join(root, 'docs/assets-manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  return manifest;
}

test('release asset requirement follows the package version instead of unrelated file changes', async (t) => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'resume-release-assets-version-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const git = (...args) => execFileSync('git', args, { cwd: directory, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  git('init', '--initial-branch=main');
  git('config', 'user.name', 'Release Assets Test');
  git('config', 'user.email', 'release-assets@example.invalid');
  git('config', 'commit.gpgSign', 'false');
  await writeFile(path.join(directory, 'package.json'), '{"version":"0.2.5"}\n');
  git('add', 'package.json');
  git('commit', '-m', 'initial version');
  const base = git('rev-parse', 'HEAD');
  assert.equal(releaseAssetsRequiredBetween(base, base, directory), false);
  await writeFile(path.join(directory, 'package.json'), '{"version":"0.2.6"}\n');
  git('commit', '-am', 'next version');
  const head = git('rev-parse', 'HEAD');
  assert.equal(releaseAssetsRequiredBetween(base, head, directory), true);
  assert.throws(() => releaseAssetsRequiredBetween('main', head, directory), /full commit SHAs/);
});

test('committed LFS assets may come from another commit when version, site, and generated bytes match', async (t) => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'resume-release-assets-compare-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const generatedRoot = path.join(directory, 'generated');
  const committedRoot = path.join(directory, 'committed');
  await writeAssetFixture(generatedRoot, { commit: 'a'.repeat(40) });
  await writeAssetFixture(committedRoot, { commit: 'b'.repeat(40), lfsPointers: true });
  assert.deepEqual(await compareReleaseAssets({ committedRoot, generatedRoot, sourceSha: 'a'.repeat(40) }), {
    siteHash: 'c'.repeat(64), version: '0.3.0'
  });
});

test('release asset comparison rejects stale versions, site bytes, and LFS objects', async (t) => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'resume-release-assets-stale-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const generatedRoot = path.join(directory, 'generated');
  const committedRoot = path.join(directory, 'committed');
  await writeAssetFixture(generatedRoot, { commit: 'a'.repeat(40) });
  await writeAssetFixture(committedRoot, { commit: 'b'.repeat(40), lfsPointers: true, version: '0.2.5' });
  const compare = () => compareReleaseAssets({ committedRoot, generatedRoot, sourceSha: 'a'.repeat(40) });
  await assert.rejects(compare(), /version does not match/);

  await writeAssetFixture(committedRoot, { commit: 'b'.repeat(40), lfsPointers: true, siteHash: 'd'.repeat(64) });
  await assert.rejects(compare(), /different site bytes/);

  await writeAssetFixture(committedRoot, { commit: 'b'.repeat(40), lfsPointers: true });
  await writeFile(path.join(committedRoot, 'docs/screenshots/ja.png'), `version https://git-lfs.github.com/spec/v1\noid sha256:${'e'.repeat(64)}\nsize 10\n`);
  await assert.rejects(compare(), /committed ja screenshot bytes/);

  await writeAssetFixture(committedRoot, { commit: 'b'.repeat(40), lfsPointers: true });
  await assert.rejects(
    compareReleaseAssets({ committedRoot, generatedRoot, sourceSha: 'd'.repeat(40) }),
    /source commit does not match/
  );
});

test('promotion refuses overlapping generated and source roots', async (t) => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'resume-release-assets-promote-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  await assert.rejects(promoteReleaseAssets({
    assetRoot: directory, sourceRoot: directory, sourceSha: 'a'.repeat(40)
  }), /must be independent/);
});
